### ISSUE TITLE
Getting "exec /usr/local/bin/streamlit: exec format error" when the tasks launch followed by an exit 1

### ISSUE THREAD

**Issue by alanwill** [aws-samples/amazon-bedrock-serverless-prompt-chaining#213]
I haven't been able to get the initial deploy to fully complete yet as the ECS tasks are constantly failing with `exec /usr/local/bin/streamlit: exec format error` and hence failing the healthcheck so the deployment gets stuck in a loop. 

Any idea what could be causing this?

**Comment by clareliguori** [comment]
Are you maybe building the Docker image (via cdk deploy) from an ARM laptop, like with an Apple M2 chip? I'm guessing the Docker image is ARM, but it's trying to run in a Fargate x86 container.

**Comment by alanwill** [comment]
> Are you maybe building the Docker image (via cdk deploy) from an ARM laptop, like with an Apple M2 chip? I'm guessing the Docker image is ARM, but it's trying to run in a Fargate x86 container.

Wow that was spookily specific and also spot on! Yep that's exactly it. thanks for that major pointer, I'll build it on an EC2 instance instead. Thanks @clareliguori !

**Comment by clareliguori** [comment]
This change [e694ac9](https://github.com/aws-samples/amazon-bedrock-serverless-prompt-chaining/commit/e694ac9366aee47a9330fb9140a61ee90cd188b3) should fix it, to force CDK to build the Docker image for the right platform on your Mac.

**Comment by alanwill** [comment]
Oh awesome! Didn't know about that method 🙏🏼
